### ISSUE TITLE
Dataset releasing

### ISSUE THREAD

**Issue by shiyujin0** [andvg3/Grasp-Anything#1]
Great work! When do you plan to release the dataset or the trained model on your dataset? Thanks.

**Comment by andvg3** [comment]
Hi shiyujin0,

We greatly appreciate your interest in our dataset. Our dataset will be made publicly available soon. Please stay tuned for update!

Best regards,
An Vuong.

**Comment by mco0308** [comment]
Hi, I was wondering when your data set will be available, and I can't wait to use the data set.

**Comment by TX-Leo** [comment]
me too👀

**Comment by andvg3** [comment]
Hi, we have released our dataset. Check it out on our [website](https://airvlab.github.io/grasp-anything/).
