### ISSUE TITLE
Thiếu module hardware

### ISSUE THREAD

**Issue by Tranthanhbao198** [andvg3/Grasp-Anything#11]
Chào bạn, 
- mình có chạy thử project của bạn, thì bị báo lỗi như thế này:   File "/home/user/Grasp-Anything/train_network.py", line 16, in <module>
    from hardware.device import get_device
ModuleNotFoundError: No module named 'hardware.device'
hình như trên này bị thiếu mục hardware phải không bạn? 
- và bạn có thể giải thích câu lệnh này giúp mình được không: $ python train_network.py --dataset cornell --dataset-path data/cornell --description training_cornell --use-depth 0, tại mình thấy trong các file dataset tải về, thì không thấy dataset cornell á bạn
- và mình cũng đang muốn áp dụng lên hệ robot thật ur3+realsense, mình có xem qua video demo thì thấy hình như project này bạn cũng dùng với realsense, bạn có thể cho mình tham khảo code của hệ thực tế không? 
Mình cảm ơn nhiều

**Comment by sunt40** [comment]
I have the same problem with you, and I pip install hardware is not useful !

**Comment by Tranthanhbao198** [comment]
> I have the same problem with you, and I pip install hardware is not useful !

this is not a module that you can install via pip, this is a hardware.py file

**Comment by sunt40** [comment]
I pip install hardware and is not useful ! Can you tell me what version do you install?

**Comment by andvg3** [comment]
Hello @Tranthanhbao198 and @sunt40 ,

- For other datasets, you should visit their published sites to obtain as sometimes they are under strict access control. Cornell dataset can be obtained via [this link](https://www.kaggle.com/datasets/oneoneliu/cornell-grasp).

- The inference code for RealSense camera was partly based on our published code, though not completely. We will update our inference code for real-time robots if possible. Thank you for your request.

> I pip install hardware and is not useful ! Can you tell me what version do you install?

- Yes, it is not possible to install via pip, we will discuss and plan to release the code. Thank you!

**Comment by sunt40** [comment]
> * Yes, it is not possible to install via pip, we will discuss and plan to release the code. Thank you!
That's sounds great!  Does that mean I can't run your code now?

**Comment by andvg3** [comment]
Yes, as of now. However, you can modify some of our code to build your own to run, I think it is not too tricky.

**Comment by Tranthanhbao198** [comment]
> I pip install hardware and is not useful ! Can you tell me what version do you install?

you can take a look at this one: https://github.com/skumra/robotic-grasping

**Comment by andvg3** [comment]
Closed due to inactivity.
