### ISSUE TITLE
Issue about the number of grasps to consider per image

### ISSUE THREAD

**Issue by zyn213** [andvg3/Grasp-Anything#12]
Hi~,really impressive work! May I ask you how do you define the number of grab boxes output by the model in a multi-target scenario? In the evaluate.py file, you set n_grasps to 1 by default. For multi-target scenarios, do you need to manually judge and modify n_grasps?
![image](https://github.com/andvg3/Grasp-Anything/assets/94900013/1de510dd-5ec5-4e8b-a260-3e8f83d277d1)

**Comment by zyn213** [comment]
And it seems that the model does not support high-resolution images, is that true?
![image](https://github.com/andvg3/Grasp-Anything/assets/94900013/80a9c518-da78-4ec3-b2a1-e6f3aa78b75b)

**Comment by andvg3** [comment]
Hi @zyn213 ,

> In the evaluate.py file, you set n_grasps to 1 by default. For multi-target scenarios, do you need to manually judge and modify n_grasps?

For boosting training and inference time, we set `n_grasps` to 1. However, you can modify to your desired number and use our proposed grasp evaluation to select the best grasp. During inference, the only predicted grasp pose was generated and without manual judge, as can be seen in our [demo video](https://airvlab.github.io/grasp-anything/assets/images/ICRA24_0520_VI_fi_compressed.mp4).

> And it seems that the model does not support high-resolution images, is that true?

Again, for optimal training and inference time, we select the input size as 224 x 224. Personally, I think it is a common practice in CV and robotic tasks to consider such resolution :D. If you wish to handle higher resolution, you can modify it and train with higher resolution dataset.

Thank you!

**Comment by zyn213** [comment]
Thanks for your kind help! Wish you a smooth work!
