### ISSUE TITLE
About the use of dataset

### ISSUE THREAD

**Issue by Geo-JTao** [andvg3/Grasp-Anything#2]
Thank you very much for this outstanding work！
 the addition of text information to this dataset is interesting for language-driven grasp. 
While looking forward to the release of the dataset, I hope that you can guide us how to make better use of it
Best wishes~

**Comment by andvg3** [comment]
Hi @gjt15083576031,

Thank you very much for your interests in our dataset. Section III-D in [our paper](https://arxiv.org/pdf/2309.09818.pdf) discussed there are two possible ways to make use of Grasp-Anything.

We believe one exciting task our dataset could offer, that is, the _language-driven grasp detection_ task. With out natural language description for the scene arrangements, we can specify which object to grasp, _i.e._, "Grasp me the cup" given an image with several objects.

We're actively working for the release of our dataset. Please stay tuned for more updates!
