### ISSUE TITLE
About training GR-ConvNet on VMRD dataset

### ISSUE THREAD

**Issue by KAI1179** [andvg3/Grasp-Anything#3]
Hello!
When I trained the GR-ConvNet on VMRD dataset using the following command:
$$python train_network.py --dataset vmrd --dataset-path /data2/Datasets/VMRD_V2_fixed/ --description test_train_vmrd --use-depth 0 $$,
the best accuracy is achieved 0.13 at epoch 40, which is lower than the result reported in the paper.

Does it need any other settings to train on VMRD dataset?

**Comment by andvg3** [comment]
Hi @KAI1179,

Thank you for your interest in our work. For your issue, we conduct experiments under seen and unseen settings for VMRD, which you can observe as three columns (Seen, Unseen, H) in Table 2. We have also specified in [our repo](https://github.com/andvg3/Grasp-Anything#datasets) that all LVIS splits of other datasets will be released along with Grasp-Anything. Therefore, please stay tuned for more updates.

We hope our answer can provide an explanation for your results. Should you have more questions, please feel free to ask us.

Best regards,
An Vuong.

**Comment by KAI1179** [comment]
Thanks for your timely reply. 
Looking forward to your updates :-)
