### ISSUE TITLE
RGB-D pretrained weights?

### ISSUE THREAD

**Issue by elenacliu** [andvg3/Grasp-Anything#6]
I use your code `evaluate.py` and your pretrained weights to test my custom data. When I only use RGB data, it works well. However when I use RGB-D data, I came across this error:

<img width="1094" alt="image" src="https://github.com/andvg3/Grasp-Anything/assets/44845151/0482a96e-1514-4540-82ae-3c1fbb0b8849">

when I add depth information, it should be 4 channels. So would you release the pretrained weights trained with depth information? Looking forward to your reply.

**Comment by andvg3** [comment]
Hi @elenacliu,

Apologies for the delayed response; I've been on vacation recently. Regarding your query about the Grasp-Anything dataset: it is indeed an RGB-only dataset and, as such, does not include depth images. We acknowledge this limitation in the 'Discussion' section of our paper, particularly on page 6

> Second, our dataset currently lacks 3D point clouds.

As a result, it is not feasible to train a model that relies on depth modality using the Grasp-Anything dataset. I hope this clarifies your question, and I'm here for any further inquiries you might have.

Best regards,
An Vuong

**Comment by andvg3** [comment]
Closed due to inactivity,
