### ISSUE TITLE
Dataset Availability

### ISSUE THREAD

**Issue by sejmoonwei** [andvg3/Grasp-Anything#8]
The dataset you proposed is very meaningful and interesting, and I would like to learn more about it. However, I found that its [link ](https://airvlab.github.io/grasp-anything/docs/download/) seems to have been removed. Therefore, I am wondering if it will still be made public? Or where can I find it?

**Comment by andvg3** [comment]
Hi @sejmoonwei ,

We will publish data very soon. We are on the final stage of hosting dataset, along with the form required to access it. Please stay updated!

Best regards,
An Vuong

**Comment by sejmoonwei** [comment]
Hi @andvg3,
Thank you so much for your prompt response. I am truly excited and appreciative of your efforts to make this dataset publicly available.

**Comment by stunback** [comment]
Hello, I find that the download page of the project homepage requires filling out a form, but there is no form link. Is the dataset still in preparation?

**Comment by andvg3** [comment]
Hi @stunback,

Thank you very much for your interests. Indeed, we are working on the final step to publish the dataset. We apologize for any inconvenience this may have caused and appreciate your patience. Please stay tuned for updates!

**Comment by andvg3** [comment]
Hi, we have released our dataset. Check it out on our [website](https://airvlab.github.io/grasp-anything/).
